# Generated by Django 5.2.4 on 2025-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
